language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: boucher.samuel.c@gmail.com
  api_key:
    secure: Ok9BlR0bxQPwcVhdkjlo5Kl+6hZaVyvr8Mqj9MglD7FZiiwy30e4tFQRyVmLzPEjH6zIR6FZPpG/8GxaWlEq6XtLFAt3Y7QbXIgKLai4YYIwlVme9D9katGtZDJq5DmysgtQgY0dy+sMkBsbNxWcqdlVtjASs/3qgViM8yk/CNM=
  on:
    tags: true
    repo: scboucher/husay
