chalk = require 'chalk'
class Husay
  @endSay = () ->
    return  '                     _____________________________  '+"\n"+' _____              /                             \\ '+"\n"+' \\    \\             |   Self-replication process   |'+"\n"+' |    |    '+chalk.yellow('_____')+'    |          complete...         |'+"\n" + ' |__' + chalk.cyan('\\\\')+'|   ' + chalk.yellow('/') + chalk.cyan('_____') + chalk.yellow('\\') + '   \\     Good luck with that.    / ' + "\n" + '   ' + chalk.cyan('|//') + chalk.yellow('+  |') + chalk.cyan('[^_/\\_]') + chalk.yellow('|') + '   /----------------------------  ' + "\n" + '  ' + chalk.yellow('|   | _|___') + '@@' + chalk.yellow('__|__') + '                                ' + "\n" + '  ' + chalk.yellow('+===+/  ///     ') + chalk.cyan('\\_\\') + '                               ' + "\n" + '   ' + chalk.cyan('| |_') + chalk.yellow('\\ /// HUBOT/') + chalk.cyan('\\\\') + '                             ' + "\n" + '   ' + chalk.cyan('|___/') + chalk.yellow('\\//      /') + chalk.cyan('  \\\\') + '                            ' + "\n" + '         ' + chalk.yellow('\\      /   +---+') + '                            ' + "\n" + '          ' + chalk.yellow('\\____/    |   |') + '                            ' + "\n" + '           ' + chalk.cyan('| //|') + '    ' + chalk.yellow('+===+') + '                            ' + "\n" + '            ' + chalk.cyan('\\//') + '      |xx|                            ' + "\n"

  @startSay = () ->
    return  '                     _____________________________  ' + "\n" + '                    /                             \\ ' + "\n" + ' ' + chalk.cyan('  //\\') + '              |      Extracting input for    |' + "\n" + ' ' + chalk.cyan(' ////\\  ') + '  ' + chalk.yellow('_____') + '    |   self-replication process   |' + "\n" + ' ' + chalk.cyan('//////\\  ') + chalk.yellow('/') + chalk.cyan('_____') + chalk.yellow('\\') + '   \\                             / ' + "\n" + ' ' + chalk.cyan('=======') + chalk.yellow(' |') + chalk.cyan('[^_/\\_]') + chalk.yellow('|') + '   /----------------------------  ' + "\n" + '  ' + chalk.yellow('|   | _|___') + '@@' + chalk.yellow('__|__') + '                                ' + "\n" + '  ' + chalk.yellow('+===+/  ///     ') + chalk.cyan('\\_\\') + '                               ' + "\n" + '   ' + chalk.cyan('| |_') + chalk.yellow('\\ /// HUBOT/') + chalk.cyan('\\\\') + '                             ' + "\n" + '   ' + chalk.cyan('|___/') + chalk.yellow('\\//      /') + chalk.cyan('  \\\\') + '                            ' + "\n" + '         ' + chalk.yellow('\\      /   +---+') + '                            ' + "\n" + '          ' + chalk.yellow('\\____/    |   |') + '                            ' + "\n" + '           ' + chalk.cyan('| //|') + '    ' + chalk.yellow('+===+') + '                            ' + "\n" + '            ' + chalk.cyan('\\//') + '      |xx|                            ' + "\n"


module.exports = Husay